### ISSUE TITLE
Turret cannot hit anything it shoots at

### ISSUE THREAD

**Issue by thienan865608** [sumghai/DefensiveMachineGunTurretPack#7] opened 2021-04-27 04:42 UTC
**Describe the bug:**  
hi, some reason, i dont know, long time i not play, but now, my turet cant hit anything,turet can fire but not hit, look like a accuracy = 0. Frist time the enemy is a little dog, i think is normal, but i try test with a raid, 2 turet cant even hit 1 :(((((

**Expected behavior:**  
 can u fix that, pls?

**Steps to reproduce:**  

1.i dont know :((((
2.
3.

**Additional information:**
 https://imgur.com/gallery/n5LhUga

## System and Game Configuration
**Operating System:**  Microsoft Windows 10 (64-bit)
**Physical RAM:**  16.0 GB
**RimWorld base game version:**  1.2.2900
**RimWorld DLCs loaded:**  none
**DMGTP mod version:**  1.6.6
**DMGTP mod downloaded from:** Steam
**Your mod list:**  Harmony newest on steam, core, hugsLib 8.0.1, CE 1.2.3.6, DMGTP 1.6.6, .....

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, DMGTP and its dependencies
- [x] I am NOT running any mods with known incompatibilities with DMGTP
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if DMGTP is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment] 2021-04-27 22:16
> 1.i dont know :((((

I can't really fix an issue that you claim to be unable to reproduce.

How far away (in cells) were the dog and raiders?

When you open the properties window of the turret, what do the stats say about turret accuracy?

Does it occur for all DMGTP turrets?

Does it occur for any other vanilla or CE turrets?

**Comment by sumghai** [comment] 2021-05-08 01:39
User did not provide clear reproduction steps, nor did they make any attempt at following troubleshooting instructions.

Closing.

**Closed as completed by sumghai** 2021-05-08 01:39 UTC
Labels: Invalid / Won't Fix / No Follow-Up, Bug
